//Arquivo Ponto.h
//Atribui novo nome para struct ponto: Ponto
typedef struct ponto Ponto;// DEFINE O NOME DA ESTRUTURA QUE ARMAZENARÁ AS DUAS VARIÁVEIS X E Y DO TIPO FLOAT QUE ARMAZENARÃO AS COORDENADAS DO PONTO PARA "Ponto"

//Cria um novo ponto - somente ponteiro!!
Ponto *pto_cria(float x, float y); // ALOCA DINÂMICAMENTE UM ESPAÇO PARA ARMAZENAR OS VALORES DE DUAS VARIÁVEIS DO TIPO FLOAT QUE ARMAZENAM AS CORDENADAS X E Y DA STRUCT PONTO

//Libera um ponto
void pto_libera(Ponto *p);// LIBERA O ESPAÇO DA MEMÓRIA ONDE ESTÃO ARMAZENADOS OS DADOS DAS VARIÁVEIS ALOCADAS DINÂMICAMENTE ATRVÉS DA FUNÇÃO

//Atribui os valores "x" e "y" a um ponto
void pto_acessa(Ponto *p, float *x, float *y);// ACESSA O CONTEÚDO DAS VARIÁVEIS X E Y DA DETERMINADA ESTRUTURA PONTO ATRAVÉS DE PONTEIROS RECEBENDO SEUS RESPECTIVOS VALORES POR REFERÊNCIA

//Atribui os valores "x" e "y" a um ponto
void pto_atribui(Ponto *p, float x, float y);// ATRIBUI ÀS VARIÁVEIS X E Y DA DETERMINADA ESTRUTURA OS VALORES PASSADOS POR CÓPIA

//Calcula a distância entre dois pontos
float pto_distancia(Ponto *p1, Ponto *p2);//RECEBE COMO REFERÊNCIA AS DUAS ESTRUTURAS p1 E p2 (SEUS VALORES DE X E DE Y) E CALCULA PRIMEIRO O VALOR DA DIFERENÇA ENTRE AS COORDENADAS X, A DIFERENÇA ENTRE AS COORDENADAS Y, EM SEGUIDA CALCULA A RAIZ QUADRADA DO QUADRADO DOS VALORES DAS DIFRERENÇAS (CÁLCULO DA HIPOTENUSA - PITÁGORAS) E RETORNA O VALOR DO CÁLCULO
